### ISSUE TITLE
Is there a way to make it work in Chrome? (With Bing Chat Unblocker)

### ISSUE THREAD

**Issue by vibl** [benf2004/Bing-Chat-History#10]
Bing can be used in Chrome with the Bing Chat Unblocker extension.

Unfortunately, Bing-Chat-History does not seem to work when used in Chrome. Conversations with Bing Chat don't appear in the extension page.

Is there a way to make it work in Chrome?

**Comment by benf2004** [comment]
Been working on it with little success so far

**Comment by benf2004** [comment]
It's working for me!

**Comment by vibl** [comment]
Yes, it does work now. No idea why it didn't.

Thank you for this extension! I use it every day.
