### ISSUE TITLE
What happens when local.storage exceeds 5MB?

### ISSUE THREAD

**Issue by mdkim** [benf2004/Bing-Chat-History#14]
Did a cursory check to see if this was catching "QuotaExceededError" etc, couldn't find anything. Will it conspicuously alert that there was an error, or will it quietly stop storing any more?

**Comment by benf2004** [comment]
The extension has the “unlimitedStorage” permission so there is not a limit. Additionally, I have read that this limit is not really “enforced”, at least on chrome.
