### ISSUE TITLE
Extension does not recognize chat (links/image) from Bing image creator feature.

### ISSUE THREAD

**Issue by jxxvxs** [benf2004/Bing-Chat-History#17]
The new Bing image creator feature in Bing Chat allows you to generate images based on your text input. You can use it to create or draw anything you want, such as animals, landscapes, cartoons, logos, etc. To use the feature, you just need to be in creative mode and telling it to generate images and it will be attached like below :

![image](https://user-images.githubusercontent.com/82653898/227692553-ad863624-45d8-4779-9bb2-957bf6ffe233.png)

However, The extension does not detect (?) the image creator feature. The extension is designed to save the text messages and links in the chat box, but it does not recognize the images generated by Bing or the links embedded to them. This means that if you use the image creator feature in your chat, the extension will not save the links to them in your chat history. In my opinion, this is a limitation of the extension that needs to be fixed.

![image](https://user-images.githubusercontent.com/82653898/227694618-9329467a-1229-4584-8693-eceaf89bd690.png)

**Comment by benf2004** [comment]
Merging with #23
