### ISSUE TITLE
Does not save images in chat

### ISSUE THREAD

**Issue by neoconstel** [benf2004/Bing-Chat-History#18]
![Screenshot from 2023-03-25 08-34-39](https://user-images.githubusercontent.com/57400695/227704048-acbb9d9b-578f-45df-a3a2-bef96ca7f9ec.png)
![Screenshot_2023-03-25_07-35-14](https://user-images.githubusercontent.com/57400695/227704067-87b9c451-5bf3-4427-acc9-7da010951edf.png)

**Comment by benf2004** [comment]
Merging with #23
