### ISSUE TITLE
Any way to recover deleted chat history?

### ISSUE THREAD

**Issue by weavermarquez** [benf2004/Bing-Chat-History#21]
Unfortunately, I deleted the wrong chat. I'm pretty sure it's related to #15 but it could also have been my bad. I really put a lot of effort into the analysis for that one and I'm pretty sad that I accidentally deleted it.

If storage works with internal files, maybe we could have an option to place Deleted chat history into Trash Bin?

**Comment by benf2004** [comment]
Unfortunately, there’s not a way to recover a chat at this time. The extension uses the browser storage API. Once it’s gone, it’s gone. 

I am working on cloud storage for the sister extension to this one (ChatGPT Prompt Genius). Then it should be much easier to recover deleted threads.
