### ISSUE TITLE
chats randomly disappear from history when i click on bookmarks

### ISSUE THREAD

**Issue by wickedcandy** [benf2004/Bing-Chat-History#9]
if i click on the bookmarks button then click to return to the item list messages will suddenly just not be there anymore. i did it again and now i only have one message left.

**Comment by benf2004** [comment]
Hi, does refreshing the page fix this issue?

What browser are you on?

**Comment by xilopaint** [comment]
I've been facing similar issue with Microsoft Edge for macOS. Chats are disappearing randomly. Not sure what is causing it but the extension doesn't work for me.

**Comment by benf2004** [comment]
Hi, I am working on updating the extension so the local chat history is more closely synced with ChatGPT. This update should come within the week.
